module.exports = {
  darkMode: 'class',
  content: ['./index.html', './assets/js/**/*.js'],
  theme: {
    extend: {
      colors: {
        'surface-container-low': '#1a1d15',
        'surface-variant': '#33362d',
        error: '#ffb4ab',
        'tertiary-fixed': '#fde094',
        'surface-bright': '#373a31',
        'on-error-container': '#ffdad6',
        'on-tertiary-fixed-variant': '#574505',
        'inverse-on-surface': '#2e3129',
        'on-surface': '#e2e4d7',
        'primary-fixed': '#ffdf9b',
        primary: '#e6c375',
        'error-container': '#93000a',
        secondary: '#c6c8b6',
        'outline-variant': '#4d4639',
        'on-surface-variant': '#d0c5b4',
        'on-tertiary': '#3d2f00',
        'on-primary-fixed': '#251a00',
        'on-secondary-fixed': '#1a1d12',
        'inverse-surface': '#e2e4d7',
        'surface-container': '#1e2119',
        tertiary: '#e0c57b',
        'surface-container-highest': '#33362d',
        'tertiary-fixed-dim': '#dfc47a',
        'surface-tint': '#e5c274',
        outline: '#99907f',
        'secondary-container': '#474a3d',
        'secondary-fixed-dim': '#c6c8b6',
        'surface-container-lowest': '#0c0f08',
        'on-secondary-container': '#b8baa9',
        'on-secondary': '#2f3225',
        'on-tertiary-fixed': '#241a00',
        surface: '#11140d',
        'secondary-fixed': '#e2e4d2',
        'primary-fixed-dim': '#e5c274',
        'surface-container-high': '#282b23',
        'on-primary': '#3f2e00',
        'surface-dim': '#11140d',
        background: '#11140d',
        'on-tertiary-container': '#503e00',
        'on-error': '#690005',
        'inverse-primary': '#755b17',
        'on-background': '#e2e4d7',
        'on-primary-fixed-variant': '#5a4300',
        'primary-container': '#c9a85d',
        'on-primary-container': '#523d00',
        'tertiary-container': '#c3aa63',
        'on-secondary-fixed-variant': '#45483b'
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem'
      },
      spacing: {
        'space-xs': '0.5rem',
        'space-lg': '3rem',
        'space-xl': '5rem',
        'gutter-mobile': '1rem',
        'space-md': '1.75rem',
        gutter: '2rem',
        margin: '3.5rem',
        'space-sm': '1rem',
        'margin-mobile': '1.25rem'
      },
      fontFamily: {
        'label-caps': ['Cormorant SC', 'EB Garamond', 'serif'],
        'body-md': ['Cormorant Garamond', 'EB Garamond', 'serif'],
        'display-romantic': ['Great Vibes', 'cursive'],
        'headline-lg': ['EB Garamond', 'serif'],
        'body-lg': ['Cormorant Garamond', 'EB Garamond', 'serif'],
        'display-romantic-mobile': ['Great Vibes', 'cursive'],
        'label-italic': ['Cormorant Garamond', 'EB Garamond', 'serif'],
        'headline-sm': ['Cormorant SC', 'EB Garamond', 'serif'],
        'headline-lg-mobile': ['EB Garamond', 'serif'],
        'headline-md': ['EB Garamond', 'serif']
      },
      fontSize: {
        'label-caps': ['13px', { lineHeight: '18px', letterSpacing: '0.25em', fontWeight: '600' }],
        'label-italic': ['15px', { lineHeight: '22px', letterSpacing: '0.03em', fontWeight: '400' }],
        'body-md': ['17px', { lineHeight: '28px', letterSpacing: '0.02em', fontWeight: '400' }],
        'display-romantic': ['68px', { lineHeight: '74px', letterSpacing: '0.02em', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '0.2em', fontWeight: '400' }],
        'body-lg': ['20px', { lineHeight: '32px', letterSpacing: '0.01em', fontWeight: '400' }],
        'headline-sm': ['18px', { lineHeight: '26px', letterSpacing: '0.12em', fontWeight: '500' }],
        'headline-md': ['22px', { lineHeight: '30px', letterSpacing: '0.15em', fontWeight: '500' }]
      }
    }
  }
};